Repository GreenStep99/Backend, pull requests merged in 2022-09, with the labels that each got.

#22 fix: 파일 형식 yml 에서 yaml로 변경
  appspec.yaml
Labels: bug

#39 fix: 서버 요청 테스트
  src/main/java/com/hanghae/greenstep/test/Test1.java
Labels: bug

#43 feat: SubmitMission 목록 조회 기능 추가
  src/main/java/com/hanghae/greenstep/admin/AdminController.java
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/admin/SubmitMissionResponseDto.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMission.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionRepository.java
Labels: enhancement

#49 Feature/get feed
  src/main/java/com/hanghae/greenstep/admin/AdminController.java
  src/main/java/com/hanghae/greenstep/admin/SubmitMissionResponseDto.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMission.java
Labels: bug

#55 feat: 전체 feed 조회 기능 추가
  src/main/java/com/hanghae/greenstep/clap/ClapRepository.java
  src/main/java/com/hanghae/greenstep/feed/FeedController.java
  src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
  src/main/java/com/hanghae/greenstep/feed/FeedResponseDto.java
  src/main/java/com/hanghae/greenstep/feed/FeedService.java
Labels: enhancement

#62 feat: 박수를 호출 할때마다 증가 감소하는 기능 추가(+피드별 박수 개수 업데이트)
  src/main/java/com/hanghae/greenstep/clap/Clap.java
  src/main/java/com/hanghae/greenstep/clap/ClapController.java
  src/main/java/com/hanghae/greenstep/clap/ClapRepository.java
  src/main/java/com/hanghae/greenstep/clap/ClapRequestDto.java
  src/main/java/com/hanghae/greenstep/clap/ClapService.java
  src/main/java/com/hanghae/greenstep/feed/Feed.java
Labels: enhancement

#63 fix: hearByMe_isEdit -> clapByMe_isEdit로 변수 명 변경
  src/main/java/com/hanghae/greenstep/feed/FeedService.java
Labels: bug

#64 refactor: 박수 기능 리펙토링
  src/main/java/com/hanghae/greenstep/clap/ClapController.java
  src/main/java/com/hanghae/greenstep/clap/ClapRepository.java
  src/main/java/com/hanghae/greenstep/clap/ClapService.java
Labels: refactor

#66 fix: clap repository 예약어 변경
  src/main/java/com/hanghae/greenstep/clap/ClapRepository.java
  src/main/java/com/hanghae/greenstep/feed/FeedService.java
Labels: bug

#70 fix: feed 전체 조회 무한스크롤 기능 추가
  src/main/java/com/hanghae/greenstep/feed/FeedController.java
  src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
  src/main/java/com/hanghae/greenstep/feed/FeedService.java
Labels: bug

#71 fix: 전체Feed 조회 무한 스크롤 예약어 문제 수정.(feedRepository 예약어 'in' 삭제)
  src/main/java/com/hanghae/greenstep/feed/FeedController.java
  src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
  src/main/java/com/hanghae/greenstep/feed/FeedService.java
Labels: bug

#73 feat: feed 카테고리별 조회(무한 스크롤 기능 추가)
  src/main/java/com/hanghae/greenstep/feed/Feed.java
  src/main/java/com/hanghae/greenstep/feed/FeedController.java
  src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
  src/main/java/com/hanghae/greenstep/feed/FeedService.java
Labels: enhancement

#78 feat: 미션 인증 완료 횟수 기준으로 내림차순으로 유저 정렬 기능 추가
  src/main/java/com/hanghae/greenstep/rank/RankController.java
  src/main/java/com/hanghae/greenstep/rank/RankService.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionRepository.java
Labels: enhancement

#88 Feature/admin page
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionResponseDto.java
Labels: bug

#89 fix: SubmitMission 테이블에 missionName, missionType 칼럼 추가
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMission.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionResponseDto.java
Labels: bug

#91 feat: 미션 포인트 획득 기능 추가
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/member/Member.java
Labels: enhancement

#94 feat: 일일 포인트 랭킹, 주간 포인트 랭킹, 전체 포인트 랭킹 조회 추가
  src/main/java/com/hanghae/greenstep/member/MemberRepository.java
  src/main/java/com/hanghae/greenstep/rank/RankController.java
  src/main/java/com/hanghae/greenstep/rank/RankService.java
Labels: enhancement

#98 fix: 총, 일간, 주간 미션포인트 default 값이 null 인 문제 수정.(0으로 수정)
  src/main/java/com/hanghae/greenstep/member/Member.java
Labels: bug

#103 fix: 모든 랭킹 상위 3명만 조회 + 리펙토링
  src/main/java/com/hanghae/greenstep/member/MemberRepository.java
  src/main/java/com/hanghae/greenstep/rank/MemberRankResponseDto.java
  src/main/java/com/hanghae/greenstep/rank/RankService.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionRepository.java
Labels: enhancement, refactor

#110 fix: 사용안하는 랭킹 api 기능들 삭제
  src/main/java/com/hanghae/greenstep/member/MemberRepository.java
  src/main/java/com/hanghae/greenstep/rank/RankController.java
  src/main/java/com/hanghae/greenstep/rank/RankService.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionRepository.java
Labels: refactor

#111 Feature/mission point
  src/main/java/com/hanghae/greenstep/member/Member.java
  src/main/java/com/hanghae/greenstep/scheduler/MissionScheduler.java
Labels: bug, refactor

#116 refactor: @transactional(read"Only = true) 읽기 전용 트랜잭션 사용을 통한 조회 속도 최적화
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/feed/FeedService.java
  src/main/java/com/hanghae/greenstep/member/MemberService.java
  src/main/java/com/hanghae/greenstep/rank/RankService.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionService.java
Labels: refactor

#120 fix: cors https 클라우드프론트, 로드밸런서 주소 추가
  src/main/java/com/hanghae/greenstep/configuration/WebMvcConfiguration.java
Labels: bug

#122 Feature/optimization
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/admin/ApplicationEventPublisher.java
  src/main/java/com/hanghae/greenstep/admin/VerifiedEventHandler.java
  src/main/java/com/hanghae/greenstep/configuration/SecurityConfiguration.java
  src/main/java/com/hanghae/greenstep/shared/Check.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionRepository.java
Labels: bug, refactor

#125 fix: FeedService 의 n:1 연관관계 매핑 n+1 문제 fetch join으로 해결
  src/main/java/com/hanghae/greenstep/clap/ClapService.java
  src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
  src/main/java/com/hanghae/greenstep/feed/FeedService.java
Labels: bug, refactor

#126 Feature/optimization
  src/main/java/com/hanghae/greenstep/mission/MissionService.java
  src/main/java/com/hanghae/greenstep/rank/RankService.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionService.java
Labels: documentation, wontfix

#132 feat: 깃액션 자동 배포 적용 유무를 확인하기 위한 getTest api 생성
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionController.java
  src/main/java/com/hanghae/greenstep/test/TestController.java
Labels: enhancement

#133 fix: weeklyMissionPoint 칼럼 삭제
  src/main/java/com/hanghae/greenstep/member/Member.java
Labels: refactor

#134 feat: 로그아웃, 회원탈퇴 기능 추가
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/clap/Clap.java
  src/main/java/com/hanghae/greenstep/clap/ClapRepository.java
  src/main/java/com/hanghae/greenstep/clap/ClapService.java
  src/main/java/com/hanghae/greenstep/feed/FeedService.java
  src/main/java/com/hanghae/greenstep/jwt/RefreshTokenRepository.java
  src/main/java/com/hanghae/greenstep/kakaoLogin/KakaoSocialController.java
  src/main/java/com/hanghae/greenstep/kakaoLogin/KakaoSocialService.java
  src/main/java/com/hanghae/greenstep/kakaoShare/Dto/LinkDto.java
  src/main/java/com/hanghae/greenstep/kakaoShare/Dto/SocialDto.java
  src/main/java/com/hanghae/greenstep/kakaoShare/KakaoShareService.java
  src/main/java/com/hanghae/greenstep/member/Member.java
  src/main/java/com/hanghae/greenstep/member/MemberController.java
  src/main/java/com/hanghae/greenstep/member/MemberService.java
Labels: enhancement

#137 feat: [SSE] 실시간 알림 기능 구현
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/clap/ClapService.java
  src/main/java/com/hanghae/greenstep/exception/ErrorCode.java
  src/main/java/com/hanghae/greenstep/member/Member.java
  src/main/java/com/hanghae/greenstep/notice/EmitterRepository.java
  src/main/java/com/hanghae/greenstep/notice/EmitterRepositoryImpl.java
  src/main/java/com/hanghae/greenstep/notice/Notification.java
  src/main/java/com/hanghae/greenstep/notice/NotificationController.java
  src/main/java/com/hanghae/greenstep/notice/NotificationCountDto.java
  src/main/java/com/hanghae/greenstep/notice/NotificationRepository.java
  src/main/java/com/hanghae/greenstep/notice/NotificationResponseDto.java
  src/main/java/com/hanghae/greenstep/notice/NotificationService.java
  src/main/java/com/hanghae/greenstep/shared/notice/NotificationContent.java
  src/main/java/com/hanghae/greenstep/shared/notice/NotificationType.java
  src/main/java/com/hanghae/greenstep/shared/notice/RelatedURL.java
  src/test/java/com/hanghae/greenstep/notice/EmitterRepositoryImplTest.java
  src/test/java/com/hanghae/greenstep/notice/embeddable/NotificationContentTest.java
  src/test/java/com/hanghae/greenstep/notice/embeddable/RelatedURLTest.java
Labels: enhancement

#138 fix: 알림을 받는 멤버가 박수 받는 멤버가 아닌 박수를 주는 멤버인 것을 확인. 박수 받는 멤버를 알림을 받는 멤버로 변경
  src/main/java/com/hanghae/greenstep/clap/ClapService.java
Labels: bug

#140 fix: 프론트 측 eventresource 미구현으로 인한 코드 에러들 임시 주석처리
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/clap/ClapService.java
Labels: bug

#141 fix: 빌드오류 @EqualsAndHashCode(of = "id") 주석처리
  src/main/java/com/hanghae/greenstep/notice/Notification.java
Labels: bug

#143 style: 유저 가입 일시 추가
  src/main/java/com/hanghae/greenstep/member/Member.java
Labels: style

#145 fix: 배포 전 남아있는 파일 삭제 로직 추가
  beforeInstall.sh
Labels: enhancement

#146 fix : '이름'이 실제 성함일 수 있음을 고려하여 이름을 입력하여 주세요 로 변경하여 DB에 저장
  src/main/java/com/hanghae/greenstep/kakaoLogin/KakaoSocialService.java
  src/main/java/com/hanghae/greenstep/member/Member.java
Labels: bug

#148 refactor: 피드백에 따른 Service, Controller 각각 리턴값 정리
  src/main/java/com/hanghae/greenstep/admin/AdminController.java
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/clap/ClapController.java
  src/main/java/com/hanghae/greenstep/clap/ClapService.java
  src/main/java/com/hanghae/greenstep/feed/FeedController.java
  src/main/java/com/hanghae/greenstep/feed/FeedService.java
  src/main/java/com/hanghae/greenstep/image/ImageController.java
  src/main/java/com/hanghae/greenstep/kakaoLogin/KakaoSocialController.java
  src/main/java/com/hanghae/greenstep/kakaoLogin/KakaoSocialService.java
  src/main/java/com/hanghae/greenstep/kakaoShare/KakaoShareController.java
  src/main/java/com/hanghae/greenstep/kakaoShare/KakaoShareService.java
  src/main/java/com/hanghae/greenstep/member/MemberController.java
  src/main/java/com/hanghae/greenstep/member/MemberService.java
  src/main/java/com/hanghae/greenstep/mission/MissionController.java
  src/main/java/com/hanghae/greenstep/mission/MissionService.java
  src/main/java/com/hanghae/greenstep/notice/NotificationService.java
  src/main/java/com/hanghae/greenstep/rank/RankController.java
  src/main/java/com/hanghae/greenstep/rank/RankService.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionController.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionService.java
Labels: refactor, style

#151 feat: 인증샷 숨기기 시, feed도 숨겨지는 기능 추가
  src/main/java/com/hanghae/greenstep/feed/Feed.java
  src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
  src/main/java/com/hanghae/greenstep/feed/FeedService.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMission.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionService.java
Labels: enhancement, refactor

#152 Fix/profile update
  src/main/java/com/hanghae/greenstep/member/Member.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMission.java
Labels: bug

#163 fix: 사용하지 않는 CommonService클래스 삭제
  src/main/java/com/hanghae/greenstep/notice/NotificationController.java
  src/main/java/com/hanghae/greenstep/notice/NotificationService.java
  src/main/java/com/hanghae/greenstep/shared/CommonService.java
Labels: refactor

#164 Feature/deploy
  appspec.yml
  beforeInstall.sh
Labels: bug

#165 fix: nickname, name값의 정규식 필터 추가
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/exception/ErrorCode.java
  src/main/java/com/hanghae/greenstep/kakaoAPI/KakaoSocialService.java
  src/main/java/com/hanghae/greenstep/member/MemberService.java
  src/main/java/com/hanghae/greenstep/mission/Dto/MissionResponseDto.java
  src/main/java/com/hanghae/greenstep/mission/Mission.java
  src/main/java/com/hanghae/greenstep/mission/MissionService.java
Labels: bug, enhancement

#169 Revert "feat: 카카오톡 푸시 알람 API 추가 #135"
  .gitignore
  build.gradle
  src/main/java/com/hanghae/greenstep/admin/AdminController.java
  src/main/java/com/hanghae/greenstep/configuration/WebMvcConfiguration.java
  src/main/java/com/hanghae/greenstep/feed/FeedRepository.java
  src/main/java/com/hanghae/greenstep/kakaoAPI/Dto/CustomFieldDto.java
  src/main/java/com/hanghae/greenstep/kakaoAPI/Dto/PushContentDto.java
  src/main/java/com/hanghae/greenstep/kakaoAPI/Dto/PushMsgDto.java
  src/main/java/com/hanghae/greenstep/kakaoAPI/Dto/PushTokenDto.java
  src/main/java/com/hanghae/greenstep/kakaoAPI/FcmInitializer.java
  src/main/java/com/hanghae/greenstep/kakaoAPI/FcmService.java
  src/main/java/com/hanghae/greenstep/kakaoAPI/KakaoPushAlertService.java
  src/main/java/com/hanghae/greenstep/kakaoAPI/KakaoSocialController.java
  src/main/java/com/hanghae/greenstep/kakaoAPI/KakaoSocialService.java
  src/main/java/com/hanghae/greenstep/kakaoAPI/PushStatus.java
  src/main/java/com/hanghae/greenstep/member/Dto/MemberRequestDto.java
  src/main/java/com/hanghae/greenstep/member/Member.java
  src/main/java/com/hanghae/greenstep/mission/MissionService.java
  src/main/java/com/hanghae/greenstep/notice/NotificationCountDto.java
  src/main/java/com/hanghae/greenstep/notice/NotificationResponseDto.java
  src/main/java/com/hanghae/greenstep/shared/mail/EmailService.java
  src/main/java/com/hanghae/greenstep/submitMission/ImageService.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionService.java
  src/main/resources/firebase/greenstep-6c162-firebase-adminsdk-utsuy-22bdb126de.json
  src/main/resources/firebase/pushMsg.json
Labels: bug

#171 fix: 서버 실행 안되는 문제 수정
  deploy.sh
Labels: bug, refactor

#172 Revert "fix: 서버 실행 안되는 문제 수정"
  deploy.sh
Labels: bug

#173 Revert "fix: 배포 자동화 적용시 nohup.out 파일 생성되게 수정"
  deploy.sh
Labels: bug

#178 fix: 에러로그만 확인기능 추가
  src/main/resources/logback.xml
Labels: enhancement, refactor

#179 fix: resource 디렉토리 생성 기능 삭제
  .github/workflows/depoly.yml
Labels: bug, refactor

#185 fix: logback.xml 파일 값 가상변수에서 가져오는 방식으로 변경
  .github/workflows/depoly.yml
  src/main/resources/logback.xml
Labels: enhancement

#187 fix: 빌드 오류 수정
  .github/workflows/depoly.yml
  logs/access_log.2022-09-20.log
  src/main/resources/logback.xml
Labels: bug

#189 fix: 미션 인가시 알림 재추가
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
Labels: enhancement

#190 fix: 알림 시 이미지 url 도 보낼수 있게 추가
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/clap/ClapService.java
  src/main/java/com/hanghae/greenstep/exception/ErrorCode.java
  src/main/java/com/hanghae/greenstep/notice/Dto/NotificationDto.java
  src/main/java/com/hanghae/greenstep/notice/Dto/NotificationRequestDto.java
  src/main/java/com/hanghae/greenstep/notice/Notification.java
  src/main/java/com/hanghae/greenstep/notice/NotificationService.java
  src/main/java/com/hanghae/greenstep/notice/RelatedIMGURL.java
Labels: enhancement

#191 feat: 알림 생성 시간 표시되게 추가
  src/main/java/com/hanghae/greenstep/clap/ClapService.java
  src/main/java/com/hanghae/greenstep/notice/Dto/NotificationDto.java
  src/main/java/com/hanghae/greenstep/notice/Notification.java
Labels: enhancement

#192 fix: 관리자 인가시 보내는 알림창의 imgUrl null값으로 변경
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
Labels: refactor

#193 Revert "fix: 관리자 인가시 보내는 알림창의 imgUrl null값으로 변경"
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
Labels: bug

#198 feature: 로그확인 내역 변경
  src/main/java/com/hanghae/greenstep/kakaoAPI/KakaoSocialService.java
  src/main/resources/logback.xml
Labels: enhancement

#200 revert:로그내역 예전 방식으로 변경
  src/main/resources/logback.xml
Labels: enhancement

#202 fix: 박수 알림 주소 변경
  src/main/java/com/hanghae/greenstep/clap/ClapService.java
Labels: bug

#205 feat: 미션인증 거부시 알림 전송 추가
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
Labels: enhancement

#214 fix:알림 테이블 isOpen 칼럼 생성 & 알림목록 열람시 해당 목록의 알림 리스트 들 모두 열람 확인 처리 & 알림 카…
  src/main/java/com/hanghae/greenstep/notice/Notification.java
  src/main/java/com/hanghae/greenstep/notice/NotificationController.java
  src/main/java/com/hanghae/greenstep/notice/NotificationRepository.java
  src/main/java/com/hanghae/greenstep/notice/NotificationService.java
Labels: enhancement
