Repository GreenStep99/Backend, pull requests merged in 2022-08, with the labels that each got.

#2 feat: 프로필 수정 기능 추가
  src/main/java/com/hanghae/greenstep/jwt/TokenProvider.java
  src/main/java/com/hanghae/greenstep/member/LoginRequestDto.java
  src/main/java/com/hanghae/greenstep/member/Member.java
  src/main/java/com/hanghae/greenstep/member/MemberController.java
  src/main/java/com/hanghae/greenstep/member/MemberRepository.java
  src/main/java/com/hanghae/greenstep/member/MemberRequestDto.java
  src/main/java/com/hanghae/greenstep/member/MemberService.java
  src/main/java/com/hanghae/greenstep/shared/Check.java
Labels: enhancement, refactor

#5 자동 빌드 구현
  .github/workflows/depoly.yml
  .github/workflows/main.yml
Labels: enhancement

#8 ignore 처리된 properties 생성
  .github/workflows/depoly.yml
Labels: refactor

#11 fix: aws-region 값을 받아오지 못하는 문제 수정
  .github/workflows/depoly.yml
Labels: bug

#20 fix: 엑세스키와 시크릿키 경로 재정의
  .github/workflows/depoly.yml
Labels: bug
