Repository GreenStep99/Backend, pull requests merged in 2022-10, with the labels that each got.

#215 feat: 피드 추가시 데일리 포인트 증가
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/feed/FeedService.java
  src/main/java/com/hanghae/greenstep/member/Member.java
Labels: enhancement

#216 feat: 알림 선택 삭제 기능 추가
  src/main/java/com/hanghae/greenstep/configuration/SecurityConfiguration.java
  src/main/java/com/hanghae/greenstep/notice/NotificationController.java
  src/main/java/com/hanghae/greenstep/notice/NotificationService.java
Labels: enhancement

#217 fix: 중복로그인 테스트 코드 머지된거 삭제
  src/main/java/com/hanghae/greenstep/configuration/SecurityConfiguration.java
Labels: bug

#218 fix: 세미클론 추가
  src/main/java/com/hanghae/greenstep/configuration/SecurityConfiguration.java
Labels: bug

#219 fix: 알림 삭제 시 exception 처리 피드 오류로 되어있는 걸 알림 오류로 수정
  src/main/java/com/hanghae/greenstep/notice/NotificationService.java
Labels: refactor

#220 refactor: 불필요한 코드 및 주석 제거
  src/main/java/com/hanghae/greenstep/notice/EmitterRepository.java
  src/main/java/com/hanghae/greenstep/notice/EmitterRepositoryImpl.java
  src/main/java/com/hanghae/greenstep/notice/Notification.java
  src/main/java/com/hanghae/greenstep/notice/NotificationController.java
  src/main/java/com/hanghae/greenstep/notice/NotificationRepository.java
  src/main/java/com/hanghae/greenstep/notice/NotificationService.java
  src/main/java/com/hanghae/greenstep/notice/RelatedIMGURL.java
  src/main/java/com/hanghae/greenstep/notice/RelatedURL.java
Labels: refactor

#226 style : log.info 삭제 및 Slf4j 제거 import 정리
  src/main/java/com/hanghae/greenstep/admin/AdminService.java
  src/main/java/com/hanghae/greenstep/configuration/SecurityConfiguration.java
  src/main/java/com/hanghae/greenstep/configuration/WebMvcConfiguration.java
  src/main/java/com/hanghae/greenstep/kakaoAPI/KakaoSocialService.java
  src/main/java/com/hanghae/greenstep/member/MemberController.java
  src/main/java/com/hanghae/greenstep/member/MemberService.java
  src/main/java/com/hanghae/greenstep/notice/NotificationController.java
  src/main/java/com/hanghae/greenstep/notice/NotificationService.java
  src/main/java/com/hanghae/greenstep/rank/RankService.java
  src/main/java/com/hanghae/greenstep/shared/Check.java
  src/main/java/com/hanghae/greenstep/shared/scheduler/ImageScheduler.java
  src/main/java/com/hanghae/greenstep/submitMission/ImageService.java
  src/main/java/com/hanghae/greenstep/submitMission/MissionStatus.java
  src/main/java/com/hanghae/greenstep/submitMission/MissionStatusRepository.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionController.java
  src/main/java/com/hanghae/greenstep/submitMission/SubmitMissionRepository.java
Labels: style
